package com.stationly.mobile.v2

import android.content.Intent
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.core.splashscreen.SplashScreen.Companion.installSplashScreen
import com.stationly.app.AndroidPlatformAuthProvider
import com.stationly.app.App
import com.stationly.mobile.R

/**
 * The v2 host: the Android half of a contract that is one function signature.
 *
 * iOS's half is `MainViewController.kt` — twenty lines that build a
 * `PlatformAuthProvider` and hand it to `App()`. This is the same twenty lines
 * with an Activity around them. Everything the user sees below `setContent`
 * lives in `:composeApp` and is the identical code iOS runs.
 *
 * ## Why this file is in `src/staging`
 * It is the SECOND door into a live app, and it is deliberately temporary.
 * `MainActivity` stays the launcher, the deep-link target and the shipped
 * experience until AV2-3.5; this one exists so the shared UI can be exercised
 * on a real device without betting the prod build on it. The `:composeApp`
 * dependency is scoped to the staging flavour for the same reason (see
 * `build.gradle.kts` — it moves the whole Compose runtime up a minor version),
 * so this file physically cannot compile into a prod build.
 *
 * At AV2-3.5 this moves to `src/main` and becomes the launcher. See the handoff
 * note in `docs/android-v2/epics/EPIC-03-host-cutover.md` about keeping the
 * `com.stationly.mobile.MainActivity` component name alive as an alias when it
 * does: home-screen pins reference the component, not the package.
 */
class V2MainActivity : ComponentActivity() {

    /**
     * Whether the user was signed in when this Activity was FIRST created, held
     * across process death rather than recomputed.
     *
     * `AppNavigation` turns this into its `startDestination`, and a NavHost can
     * only restore a saved back stack onto the same start destination it was
     * built with. Recomputing `isLoggedIn()` on a restore asks Firebase a
     * question it may not have rehydrated the answer to yet: it says "no user",
     * the start destination flips to `auth/login`, and a back stack rooted at
     * `summary` has nowhere to land — a blank screen.
     *
     * That is not hypothetical. v1 shipped this bug and fixed it with a
     * `rememberSaveable` around the same decision (see `MainActivity.kt`). The
     * shared `AppNavigation` takes the answer as a parameter instead, so on
     * Android the saving has to happen HERE, at the host boundary.
     */
    private var startLoggedIn: Boolean = false

    /**
     * The `oobCode` from an inbound `stationly-staging://reset` link.
     *
     * Nothing routes here yet — `MainActivity` still owns every intent-filter.
     * AV2-3.4 made the SCHEME per-flavour but deliberately left the filters
     * where they are: two activities advertising one scheme puts a
     * disambiguation dialog in front of the user on every tap. AV2-3.5 moves
     * them, when there is only one door left to move them to.
     *
     * It is wired now because it is part of the host signature iOS already
     * implements, and because it makes the staging door drivable by hand:
     *
     *     adb shell am start -n com.stationly.mobile/.v2.V2MainActivity \
     *         -a android.intent.action.VIEW -d "stationly-staging://reset?oobCode=…"
     *
     * (`-n` names the component, so no intent-filter has to match — which is
     * just as well, because AV2-3.4 left every filter on `MainActivity`.)
     *
     * State rather than a plain value so a link arriving at an already-running
     * instance reaches the composition through [onNewIntent].
     */
    private var pendingResetOobCode by mutableStateOf<String?>(null)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        installSplashScreen()
        enableEdgeToEdge()

        // `Platform.initialize` is NOT called here on purpose. It runs in
        // StationlyApplication.onCreate, which Android guarantees to complete
        // before any component of the process starts — including this one. The
        // staging manifest deliberately does not override android:name, so a
        // staging build has the same Application class as prod. (Asserted
        // statically by V2HostManifestTest, since there is no runtime flag on
        // Platform to check.)
        // The Activity, not the application context: interactive Google sign-in
        // launches the account chooser for a result and needs one. Held only by
        // this Activity and by the composition, which die together, so there is
        // nothing here to leak.
        //
        // `default_web_client_id` is generated by the google-services plugin
        // from THIS flavour's google-services.json, so a staging build signs in
        // against the staging OAuth client and prod against prod's. It is read
        // here, in the module that has the generated `R`, rather than looked up
        // by name inside `:composeApp` — see the provider's KDoc for why that
        // matters to a release build specifically.
        val authProvider = AndroidPlatformAuthProvider(
            context           = this,
            googleWebClientId = getString(R.string.default_web_client_id),
        )

        startLoggedIn = if (savedInstanceState?.containsKey(KEY_START_LOGGED_IN) == true) {
            savedInstanceState.getBoolean(KEY_START_LOGGED_IN)
        } else {
            authProvider.isLoggedIn()
        }

        pendingResetOobCode = resetOobCodeFrom(intent)

        setContent {
            App(
                authProvider    = authProvider,
                startLoggedIn   = startLoggedIn,
                deepLinkOobCode = pendingResetOobCode,
            )
        }
    }

    override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        outState.putBoolean(KEY_START_LOGGED_IN, startLoggedIn)
    }

    /**
     * Every launch of this Activity arrives here rather than building a second
     * instance, because the manifest declares `launchMode="singleTask"`.
     *
     * The reasoning is inherited from `MainActivity` and is load-bearing there:
     * under the default "standard" mode a relaunch spawned a NEW task with a
     * fresh Activity, the tasks piled up (three observed at once), and returning
     * to a freshly-restored instance found the NavHost back stack empty — a
     * blank screen. It applies here identically, and this Activity additionally
     * carries its own `taskAffinity` so the two doors cannot shuffle each
     * other's back stacks while both exist.
     */
    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        setIntent(intent)
        resetOobCodeFrom(intent)?.let { pendingResetOobCode = it }
    }

    /**
     * Matched on the HOST alone, deliberately.
     *
     * v1 matched scheme AND host, with the scheme written out as a literal four
     * times — which is what broke the moment the scheme became per-flavour
     * (`stationly` on prod, `stationly-staging` on staging), and is the bug iOS
     * shipped and spent two days on. The manifest decides which schemes are
     * delivered to an Activity at all, so a second check here could only ever
     * agree with it or silently contradict it. Where a scheme genuinely has to
     * be compared, it comes from `BuildConfig.DEEP_LINK_SCHEME` and the routing
     * comes from `core`'s `parseDeepLink` — see `MainActivity.handleDeepLink`.
     */
    private fun resetOobCodeFrom(intent: Intent?): String? {
        val uri = intent?.data ?: return null
        if (uri.host != "reset") return null
        return uri.getQueryParameter("oobCode")?.takeIf { it.isNotBlank() }
    }

    private companion object {
        const val KEY_START_LOGGED_IN = "v2_start_logged_in"
    }
}
